[package]
name = "rust-esp32-std-hello"
version = "0.12.0"
authors = ["ivmarkov"]
edition = "2018"

# No xtensa in regular compiler yet
[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"

[profile.release]
# symbols are nice and they don't increase the size on Flash
debug = true
opt-level = "z"

[profile.dev]
opt-level = "s"

[dependencies]
anyhow = {version = "1", features = ["backtrace"]}
log = "0.4"
esp-idf-sys = {version = "0.13", git = "https://github.com/ivmarkov/esp-idf-sys.git"}
#esp-idf-sys = { version = "*", path = "../esp-idf-sys"}
embedded-svc = {version = "0.7", git = "https://github.com/ivmarkov/embedded-svc.git"}
#embedded-svc = {version = "*", path = "../embedded-svc"}
esp-idf-svc = {version = "0.13", git = "https://github.com/ivmarkov/esp-idf-svc.git", features = ["binstart"]}
#esp-idf-svc = {version = "*", path = "../esp-idf-svc", features = ["binstart"]}
esp-idf-hal = {version = "0.13", git = "https://github.com/ivmarkov/esp-idf-hal.git"}
#esp-idf-hal = {version = "*", path = "../esp-idf-hal"}
embedded-hal = "0.2"
embedded-graphics = "0.6"
display-interface = "0.4"
display-interface-spi = "0.4"
st7789 = "0.5"

#backtrace = {version = "0.3.56", path = "../backtrace-rs"}
#backtrace = {version = "0.3.56", git = "https://github.com/ivmarkov/backtrace-rs.git", branch = "esp-idf"}
#time = {git = "https://github.com/ivmarkov/time.git", branch = "master"}
#getrandom = {git = "https://github.com/ivmarkov/getrandom.git", branch = "0.1"}
#chrono = {git = "https://github.com/ivmarkov/chrono.git", branch = "main"}

[build-dependencies]
cargo-pio = {version = "0.12", git = "https://github.com/ivmarkov/cargo-pio"}
#cargo-pio = {version = "*", path = "../../../cargo-pio"}
anyhow = "1"
