[package]
name = "rust-esp32-std-hello"
version = "0.18.9"
authors = ["ivmarkov"]
edition = "2018"
categories = ["embedded", "hardware-support"]
keywords = ["embedded", "svc", "idf", "esp-idf", "esp32"]
description = "A demo binary crate for the ESP32 and ESP-IDF, which connects to WiFi, drives a small HTTP server and draws on a LED screen"
repository = "https://github.com/ivmarkov/rust-esp32-std-hello"
license = "MIT OR Apache-2.0"
readme = "README.md"

# No xtensa in regular compiler yet
[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"

[patch.crates-io]
smol = { git = "https://github.com/ivmarkov/smol" }
polling = { git = "https://github.com/ivmarkov/polling" }
socket2 = { git = "https://github.com/ivmarkov/socket2" }
getrandom = { version = "0.2", git = "https://github.com/ivmarkov/getrandom.git" }
getrandom1 = { version = "0.1", git = "https://github.com/ivmarkov/getrandom.git", package = "getrandom", branch = "0.1" }

[profile.release]
# symbols are nice and they don't increase the size on Flash
debug = true
opt-level = "z"

[profile.dev]
opt-level = "s"

[features]
bind = []
experimental = ["esp-idf-svc/experimental", "embedded-svc/experimental"]
native = ["esp-idf-sys/native"]

[dependencies]
anyhow = {version = "1", features = ["backtrace"]}
log = "0.4"
url = "2"
esp-idf-sys = "0.20.8"
embedded-svc = "0.10.3"
esp-idf-svc = { version = "0.23.1", features = ["binstart"] }
esp-idf-hal = "0.20"
embedded-hal = "0.2"
embedded-graphics = "0.7"
display-interface = "0.4"
display-interface-spi = "0.4"
st7789 = "0.6"
ili9341 = { version = "0.5", git = "https://github.com/yuri91/ili9341-rs" }
ssd1306 = "0.7"
smol = "1.2"

#backtrace = { git = "https://github.com/ivmarkov/backtrace-rs.git" }

[build-dependencies]
embuild = "0.24.5"
anyhow = "1"

# Future; might be possible once https://github.com/rust-lang/cargo/issues/9096 hits Cargo nightly:
# rust-esp32-ulp-hello = { path = "../rust-esp32-ulp-hello", artifact = "bin" }
