name: Rust

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '50 6 * * *'

jobs:
  # lint:
  #   name: Lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Setup | Checkout
  #       uses: actions-rs/toolchain@v1
  #     - name: Setup | Rust
  #       uses: ATiltedTree/setup-rust@v1
  #       with:
  #         toolchain: nightly
  #         components: clippy
  #     - name: Build | Lint
  #       run: cargo clippy
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Setup | Std
        run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
      - name: Setup | ldproxy
        run: cargo install ldproxy
      - name: Build | Compile
        run: cargo build --target riscv32imc-esp-espidf
